#############################
###    shared settings    ###
#############################
x-common-settings: &common
  build:
    context: .
    dockerfile: Dockerfile
  image: pomelo925/ml-app:final

  volumes:
    # GUI (optional, for QT-based windows)
    - $HOME/.Xauthority:/root/.Xauthority
    - /tmp/.X11-unix:/tmp/.X11-unix

    # shared files
    - ../yolov12-ws:/home/yolov12-ws
    - ../pretrain-weights:/ultralytics/pretrain-weights
    - ../frontend:/home/frontend
    - ../backend:/home/backend

  environment:
    - DISPLAY=${DISPLAY}

  tty: true
  stdin_open: true
  ipc: host
  privileged: true
  stop_grace_period: 1s


############################
###   shared settings    ###
############################
x-gpu-settings: &gpu
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]



############################
###   shared settings    ###
############################
x-web-settings: &web
  ports:
    - "3000:3000"
    - "8000:8000"



##############################
###   Container Services   ###
##############################
services:
  dev:
    <<: [*common, *gpu, *web]
    container_name: dev
    command: [ "bash" ]
  
  demo:
    <<: [*common, *gpu, *web]
    container_name: demo
    command: [ "bash", "-c", "cd /home/backend && uvicorn main:app --reload --host 0.0.0.0 --port 8000"]